# Generated by Django 5.1.1 on 2024-10-03 11:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_searchcriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=('%%',), size=None), size=None),
        ),
    ]
