# Generated by Django 5.1.1 on 2024-10-03 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_searchcriteria_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
