# Generated by Django 5.1.1 on 2024-10-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_searchcriteria_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=99999.99, max_digits=7),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
